version: 2.1

cache-key: &cache-key "{{ arch }}/{{ .Environment.CIRCLE_JOB }}/{{ .Environment.CACHE_GENERATION }}"

stack-build: &stack-build
  steps:
    - checkout

    - restore_cache:
        key: *cache-key

    - run:
        name: Setup Stack on MacOS
        command: |
          if [ $(uname) = Darwin ]; then
            curl -L "https://www.stackage.org/stack/osx-x86_64" | tar xz --strip-components=1 -C ~/.local/bin/
          fi

    - run:
        name: Setup GHC
        command: |
          stack --resolver $RESOLVER --no-terminal setup
          stack --resolver $RESOLVER --no-terminal update

    - run:
        name: Show Environment
        command: |
          stack --version
          stack --resolver $RESOLVER ghc -- --version

    - run:
        name: Build Dependencies
        command: |
          stack --resolver $RESOLVER --no-terminal build --test --bench --only-dependencies $EXTRA_ARGS && SUCCESS=1
          test -n "$IGNORE_FAILURE" -o -n "$SUCCESS" || false

    - save_cache:
        key: *cache-key
        paths:
          - /root/.stack
          - .stack-work

    - run:
        name: Build Project
        command: |
          stack --resolver $RESOLVER --no-terminal build --test --no-run-tests --bench --no-run-benchmarks --haddock --no-haddock-deps $EXTRA_ARGS && SUCCESS=1
          test -n "$IGNORE_FAILURE" -o -n "$SUCCESS" || false

    - run:
        name: Run Tests
        command: |
          stack --resolver $RESOLVER --no-terminal build --test $EXTRA_ARGS && SUCCESS=1
          test -n "$IGNORE_FAILURE" -o -n "$SUCCESS" || false

cabal-build: &cabal-build
  steps:
    - checkout

    - restore_cache:
        key: *cache-key

    - run:
        name: Setup Stack on MacOS
        command: |
          if [ $(uname) = Darwin ]; then
            curl -L "https://www.stackage.org/stack/osx-x86_64" | tar xz --strip-components=1 -C ~/.local/bin/
          fi

    - run:
        name: Setup GHC & Cabal
        command: |
          stack --resolver $RESOLVER --no-terminal setup
          stack --resolver $RESOLVER --no-terminal update
          stack install cabal-install
          $HOME/.local/bin/cabal new-update
          echo "export PATH=$HOME/.local/bin:$(stack --resolver $RESOLVER --no-terminal path --bin-path)" >> $BASH_ENV

    - run:
        name: Show Environment
        command: |
          stack --version
          stack --resolver $RESOLVER ghc -- --version
          cabal --version

    - run:
        name: Build Dependencies
        command: |
          cabal new-build all --enable-tests --enable-benchmarks --only-dependencies $EXTRA_ARGS && SUCCESS=1
          test -n "$IGNORE_FAILURE" -o -n "$SUCCESS" || false

    - save_cache:
        key: *cache-key
        paths:
          - /root/.stack
          - .cabal

    - run:
        name: Build Project
        command: |
          cabal new-test all --enable-tests --enable-benchmarks $EXTRA_ARGS && SUCCESS=1
          test -n "$IGNORE_FAILURE" -o -n "$SUCCESS" || false

stack-linux: &stack-linux
  <<: *stack-build
  docker:
    - image: haskell:latest

cabal-linux: &cabal-linux
  <<: *cabal-build
  docker:
    - image: haskell:latest

stack-macos: &stack-macos
  <<: *stack-build
  macos:
    xcode: "10.0"

cabal-macos: &cabal-macos
  <<: *cabal-build
  macos:
    xcode: "10.0"

jobs:
  stack-lts-7:
    <<: *stack-linux
    environment:
      RESOLVER: lts-7

  stack-lts-9:
    <<: *stack-linux
    environment:
      RESOLVER: lts-9

  stack-lts-11:
    <<: *stack-linux
    environment:
      RESOLVER: lts-11

  stack-lts-12:
    <<: *stack-linux
    environment:
      RESOLVER: lts-12

  stack-lts-13:
    <<: *stack-linux
    environment:
      RESOLVER: lts-13

  cabal-lts-7:
    <<: *cabal-linux
    environment:
      RESOLVER: lts-7

  cabal-lts-9:
    <<: *cabal-linux
    environment:
      RESOLVER: lts-9

  cabal-lts-11:
    <<: *cabal-linux
    environment:
      RESOLVER: lts-11

  cabal-lts-12:
    <<: *cabal-linux
    environment:
      RESOLVER: lts-12

  cabal-lts-13:
    <<: *cabal-linux
    environment:
      RESOLVER: lts-13

  stack-nightly:
    <<: *stack-linux
    environment:
      RESOLVER: nightly
      IGNORE_FAILURE: 1

  stack-lts-13-macos:
    <<: *stack-macos
    environment:
      RESOLVER: lts-13

workflows:
  version: 2
  build-and-test:
    jobs:
      - stack-lts-7
      - stack-lts-9
      - stack-lts-11
      - stack-lts-12
      - stack-lts-13
      - cabal-lts-7
      - cabal-lts-9
      - cabal-lts-11
      - cabal-lts-12
      - cabal-lts-13
      - stack-nightly
      # - stack-lts-13-macos
